[package]
name = "gotchi"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "async" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "async" }
reqwest = { version = "0.10.4", features = ["json"] }
serde = "1.0.105"
serde_json = "1.0.49"
rusoto_core = "0.43.0"
rusoto_dynamodb = "0.43.0"
dotenv = "0.15.0"
futures = { version = "0.3.4", features = ["compat"] }
regex = "1.3.6"
lazy_static = "1.4.0"
humantime = "2.0.0"
